---
name: "ansible-lint"

concurrency:
  group: lint-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  pull_request:
    branches: [main]
  workflow_dispatch:
  # Below is an example cron scheduler,
  # tweak it as per your requirement
  schedule:

jobs:
  lint:
    name: "ansible-lint"
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      - name: Install ansible-lint
        run: pip install ansible-lint

      - name: Run ansible-lint
        run: ansible-lint --profile=production -x sanity
